In [1]:
import math
import torch
from typing import Tuple

In [12]:
T = torch.arange(1,100 + 1, dtype= torch.float32)

In [13]:
T

tensor([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,  12.,
         13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,  23.,  24.,
         25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,  34.,  35.,  36.,
         37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,  45.,  46.,  47.,  48.,
         49.,  50.,  51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,  59.,  60.,
         61.,  62.,  63.,  64.,  65.,  66.,  67.,  68.,  69.,  70.,  71.,  72.,
         73.,  74.,  75.,  76.,  77.,  78.,  79.,  80.,  81.,  82.,  83.,  84.,
         85.,  86.,  87.,  88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,
         97.,  98.,  99., 100.])

In [14]:
f = torch.cos(((100 / T + 0.0008) / (1 + 0.0008)) * math.pi / 2) **2 

In [18]:
alpha_bar = (f/f[0])

In [20]:
betas = 1 - (alpha_bar[1:] / alpha_bar[:-1])
betas = betas.clamp(1e-6, 0.999)

In [21]:
alpha_bar = torch.cumprod(betas, dim=0)
alpha_bar

tensor([1.0000e-06, 7.8347e-07, 7.8018e-07, 7.8018e-13, 5.7158e-13, 5.7158e-19,
        2.1500e-19, 2.0414e-19, 2.0414e-25, 2.0057e-25, 2.0057e-31, 2.0057e-37,
        1.8864e-37, 1.8918e-43, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+

In [23]:
half = 128
freqs = torch.arange(half) * math.log(10000) / half
freqs

tensor([0.0000, 0.0720, 0.1439, 0.2159, 0.2878, 0.3598, 0.4317, 0.5037, 0.5756,
        0.6476, 0.7196, 0.7915, 0.8635, 0.9354, 1.0074, 1.0793, 1.1513, 1.2232,
        1.2952, 1.3672, 1.4391, 1.5111, 1.5830, 1.6550, 1.7269, 1.7989, 1.8709,
        1.9428, 2.0148, 2.0867, 2.1587, 2.2306, 2.3026, 2.3745, 2.4465, 2.5185,
        2.5904, 2.6624, 2.7343, 2.8063, 2.8782, 2.9502, 3.0221, 3.0941, 3.1661,
        3.2380, 3.3100, 3.3819, 3.4539, 3.5258, 3.5978, 3.6697, 3.7417, 3.8137,
        3.8856, 3.9576, 4.0295, 4.1015, 4.1734, 4.2454, 4.3173, 4.3893, 4.4613,
        4.5332, 4.6052, 4.6771, 4.7491, 4.8210, 4.8930, 4.9649, 5.0369, 5.1089,
        5.1808, 5.2528, 5.3247, 5.3967, 5.4686, 5.5406, 5.6126, 5.6845, 5.7565,
        5.8284, 5.9004, 5.9723, 6.0443, 6.1162, 6.1882, 6.2602, 6.3321, 6.4041,
        6.4760, 6.5480, 6.6199, 6.6919, 6.7638, 6.8358, 6.9078, 6.9797, 7.0517,
        7.1236, 7.1956, 7.2675, 7.3395, 7.4114, 7.4834, 7.5554, 7.6273, 7.6993,
        7.7712, 7.8432, 7.9151, 7.9871, 

In [34]:
x = torch.ones((5, 128, 120, 7))
x.shape

torch.Size([5, 128, 120, 7])

In [39]:
torch.nn.Conv2d(128, 128, 1)(x).view(5, 4, 128 // 4 , 120* 7).shape

torch.Size([5, 4, 32, 840])