In [14]:
import math
import torch
from typing import Tuple

In [15]:
T = torch.arange(1,100 + 1, dtype= torch.float32)

In [16]:
T

tensor([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,  12.,
         13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,  23.,  24.,
         25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,  34.,  35.,  36.,
         37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,  45.,  46.,  47.,  48.,
         49.,  50.,  51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,  59.,  60.,
         61.,  62.,  63.,  64.,  65.,  66.,  67.,  68.,  69.,  70.,  71.,  72.,
         73.,  74.,  75.,  76.,  77.,  78.,  79.,  80.,  81.,  82.,  83.,  84.,
         85.,  86.,  87.,  88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,
         97.,  98.,  99., 100.])

In [17]:
f = torch.cos(((100 / T + 0.0008) / (1 + 0.0008)) * math.pi / 2) **2 

In [5]:
alpha_bar = (f/f[0])

In [6]:
betas = 1 - (alpha_bar[1:] / alpha_bar[:-1])
betas = betas.clamp(1e-6, 0.999)

In [7]:
alpha_bar = torch.cumprod(betas, dim=0)
alpha_bar

tensor([1.0000e-06, 7.8347e-07, 7.8018e-07, 7.8018e-13, 5.7158e-13, 5.7158e-19,
        2.1500e-19, 2.0414e-19, 2.0414e-25, 2.0057e-25, 2.0057e-31, 2.0057e-37,
        1.8864e-37, 1.8918e-43, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+

In [8]:
half = 128
freqs = torch.arange(half) * math.log(10000) / half
freqs

tensor([0.0000, 0.0720, 0.1439, 0.2159, 0.2878, 0.3598, 0.4317, 0.5037, 0.5756,
        0.6476, 0.7196, 0.7915, 0.8635, 0.9354, 1.0074, 1.0793, 1.1513, 1.2232,
        1.2952, 1.3672, 1.4391, 1.5111, 1.5830, 1.6550, 1.7269, 1.7989, 1.8709,
        1.9428, 2.0148, 2.0867, 2.1587, 2.2306, 2.3026, 2.3745, 2.4465, 2.5185,
        2.5904, 2.6624, 2.7343, 2.8063, 2.8782, 2.9502, 3.0221, 3.0941, 3.1661,
        3.2380, 3.3100, 3.3819, 3.4539, 3.5258, 3.5978, 3.6697, 3.7417, 3.8137,
        3.8856, 3.9576, 4.0295, 4.1015, 4.1734, 4.2454, 4.3173, 4.3893, 4.4613,
        4.5332, 4.6052, 4.6771, 4.7491, 4.8210, 4.8930, 4.9649, 5.0369, 5.1089,
        5.1808, 5.2528, 5.3247, 5.3967, 5.4686, 5.5406, 5.6126, 5.6845, 5.7565,
        5.8284, 5.9004, 5.9723, 6.0443, 6.1162, 6.1882, 6.2602, 6.3321, 6.4041,
        6.4760, 6.5480, 6.6199, 6.6919, 6.7638, 6.8358, 6.9078, 6.9797, 7.0517,
        7.1236, 7.1956, 7.2675, 7.3395, 7.4114, 7.4834, 7.5554, 7.6273, 7.6993,
        7.7712, 7.8432, 7.9151, 7.9871, 

In [9]:
x = torch.ones((5, 128, 120, 7))
x.shape

torch.Size([5, 128, 120, 7])

In [10]:
torch.nn.Conv2d(128, 128, 1)(x).view(5, 4, 128 // 4 , 120* 7).shape

torch.Size([5, 4, 32, 840])

In [11]:
torch.nn.Conv2d(128, 128, 7)(x).shape

torch.Size([5, 128, 114, 1])

In [12]:
B = 8
total_token = 500
token_dim = 200

a = torch.rand((B, total_token, token_dim))
b = torch.rand((B, 400, token_dim))

cat = torch.concatenate([a,b], dim = 1)
cat.shape

torch.Size([8, 900, 200])

In [13]:
torch.split(cat, [400, 500], dim = 1)

(tensor([[[0.7470, 0.6178, 0.4925,  ..., 0.0205, 0.1624, 0.0647],
          [0.8063, 0.4580, 0.3925,  ..., 0.6319, 0.3252, 0.8289],
          [0.4663, 0.9972, 0.9074,  ..., 0.2387, 0.4377, 0.4900],
          ...,
          [0.4919, 0.9314, 0.0572,  ..., 0.7545, 0.1319, 0.2101],
          [0.0511, 0.4834, 0.9208,  ..., 0.0891, 0.1970, 0.5635],
          [0.6233, 0.5390, 0.9074,  ..., 0.6647, 0.9224, 0.7707]],
 
         [[0.4985, 0.0931, 0.0590,  ..., 0.0092, 0.7211, 0.6940],
          [0.1313, 0.2167, 0.6035,  ..., 0.9125, 0.2217, 0.3636],
          [0.1332, 0.2826, 0.5582,  ..., 0.9651, 0.2226, 0.4344],
          ...,
          [0.9165, 0.0094, 0.0058,  ..., 0.5871, 0.3766, 0.4977],
          [0.6841, 0.8997, 0.4889,  ..., 0.1486, 0.5874, 0.4007],
          [0.6082, 0.0543, 0.0255,  ..., 0.5297, 0.9261, 0.5759]],
 
         [[0.7621, 0.5673, 0.0670,  ..., 0.5820, 0.8702, 0.4363],
          [0.6086, 0.4246, 0.7676,  ..., 0.3886, 0.0749, 0.1349],
          [0.9410, 0.1041, 0.5529,  ...,

In [18]:
logit = torch.rand((100, 50))
logit

tensor([[0.5699, 0.5082, 0.3872,  ..., 0.0688, 0.0576, 0.5877],
        [0.5033, 0.5570, 0.0794,  ..., 0.8732, 0.3876, 0.4481],
        [0.5642, 0.7545, 0.0040,  ..., 0.4097, 0.0445, 0.2205],
        ...,
        [0.6626, 0.6711, 0.9655,  ..., 0.1690, 0.7442, 0.1730],
        [0.2411, 0.5284, 0.9110,  ..., 0.9453, 0.7859, 0.2055],
        [0.0047, 0.0454, 0.0080,  ..., 0.7915, 0.6759, 0.1510]])

In [20]:
log_prob = torch.nn.functional.log_softmax(logit, dim=-1)

In [33]:
bins= 256

th = torch.linspace(0, 1, bins+1)
th[:-1] + th[1:]

tensor([0.0039, 0.0117, 0.0195, 0.0273, 0.0352, 0.0430, 0.0508, 0.0586, 0.0664,
        0.0742, 0.0820, 0.0898, 0.0977, 0.1055, 0.1133, 0.1211, 0.1289, 0.1367,
        0.1445, 0.1523, 0.1602, 0.1680, 0.1758, 0.1836, 0.1914, 0.1992, 0.2070,
        0.2148, 0.2227, 0.2305, 0.2383, 0.2461, 0.2539, 0.2617, 0.2695, 0.2773,
        0.2852, 0.2930, 0.3008, 0.3086, 0.3164, 0.3242, 0.3320, 0.3398, 0.3477,
        0.3555, 0.3633, 0.3711, 0.3789, 0.3867, 0.3945, 0.4023, 0.4102, 0.4180,
        0.4258, 0.4336, 0.4414, 0.4492, 0.4570, 0.4648, 0.4727, 0.4805, 0.4883,
        0.4961, 0.5039, 0.5117, 0.5195, 0.5273, 0.5352, 0.5430, 0.5508, 0.5586,
        0.5664, 0.5742, 0.5820, 0.5898, 0.5977, 0.6055, 0.6133, 0.6211, 0.6289,
        0.6367, 0.6445, 0.6523, 0.6602, 0.6680, 0.6758, 0.6836, 0.6914, 0.6992,
        0.7070, 0.7148, 0.7227, 0.7305, 0.7383, 0.7461, 0.7539, 0.7617, 0.7695,
        0.7773, 0.7852, 0.7930, 0.8008, 0.8086, 0.8164, 0.8242, 0.8320, 0.8398,
        0.8477, 0.8555, 0.8633, 0.8711, 

In [34]:
bins_avg =(th[1:] + th[:-1]) / 2

In [ ]:
bins_avg

tensor([0.0020, 0.0059, 0.0098, 0.0137, 0.0176, 0.0215, 0.0254, 0.0293, 0.0332,
        0.0371, 0.0410, 0.0449, 0.0488, 0.0527, 0.0566, 0.0605, 0.0645, 0.0684,
        0.0723, 0.0762, 0.0801, 0.0840, 0.0879, 0.0918, 0.0957, 0.0996, 0.1035,
        0.1074, 0.1113, 0.1152, 0.1191, 0.1230, 0.1270, 0.1309, 0.1348, 0.1387,
        0.1426, 0.1465, 0.1504, 0.1543, 0.1582, 0.1621, 0.1660, 0.1699, 0.1738,
        0.1777, 0.1816, 0.1855, 0.1895, 0.1934, 0.1973, 0.2012, 0.2051, 0.2090,
        0.2129, 0.2168, 0.2207, 0.2246, 0.2285, 0.2324, 0.2363, 0.2402, 0.2441,
        0.2480, 0.2520, 0.2559, 0.2598, 0.2637, 0.2676, 0.2715, 0.2754, 0.2793,
        0.2832, 0.2871, 0.2910, 0.2949, 0.2988, 0.3027, 0.3066, 0.3105, 0.3145,
        0.3184, 0.3223, 0.3262, 0.3301, 0.3340, 0.3379, 0.3418, 0.3457, 0.3496,
        0.3535, 0.3574, 0.3613, 0.3652, 0.3691, 0.3730, 0.3770, 0.3809, 0.3848,
        0.3887, 0.3926, 0.3965, 0.4004, 0.4043, 0.4082, 0.4121, 0.4160, 0.4199,
        0.4238, 0.4277, 0.4316, 0.4355, 